In [5]:
import pandas as pd
import json

# Read the JSON file into a string
with open('response_003a2491-9384-11ed-80a6-890591dec723.json') as f:
    json_string = f.read()

# Parse the JSON string into a Python object
data = json.loads(json_string)

# Convert the Python object into a pandas DataFrame
df = pd.read_json('response_003a2491-9384-11ed-80a6-890591dec723.json')

df = pd.json_normalize(data, record_path =['rows'])

df

,uuid,title,jobFamily,level,focusTag,yearsOfExperience,yearsAtCompany,yearsAtLevel,offerDate,location,workArrangement,compPerspective,dmaId,countryId,exchangeRate,baseSalary,baseSalaryCurrency,totalCompensation,avgAnnualStockGrantValue,stockGrantCurrency,avgAnnualBonusValue,bonusCurrency,salesComp,negotiatedAmount,gender,ethnicity,education,otherDetails,vestingSchedule,tags,companyInfo.registered,companyInfo.icon,companyInfo.name,companyInfo.slug,companyInfo
0,d053142e-f3ee-4ce3-a70f-2e41a41963ce,Total Rewards Director,Human Resources,None,None,22,1,1.0,Tue Jul 26 2022 17:13:58 GMT+0000 (Coordinated...,"New York, NY",remote,employee,501,254,1.00000,230000.0000,USD,276000.0000,NaN,None,46000.0000,USD,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/thirtymadison.com,Thirty Madison,thirty-madison,NaN
1,d90a1b83-5175-4862-b6ab-6f88dc96b8e8,False,Human Resources,None,None,22,3,2.0,Sun Jul 24 2022 00:19:09 GMT+0000 (Coordinated...,"Minneapolis, MN",remote,employee,613,254,1.00000,190000.0000,USD,278000.0000,50000.0000,USD,38000.0000,USD,None,NaN,None,None,None,NaN,None,None,NaN,NaN,NaN,NaN,False
2,1a2103dc-5091-49f5-ba07-19f8ecacb543,False,Human Resources,False,False,5-10,2-4,2.0,Fri Jul 22 2022 17:11:28 GMT+0000 (Coordinated...,"San Francisco, CA",hybrid,employee,807,254,1.00000,138000.0000,USD,138000.0000,NaN,None,NaN,None,None,NaN,None,None,None,NaN,None,None,True,https://logo.clearbit.com/twitter.com,Twitter,twitter,NaN
3,801e091f-18ca-4f5e-a8a6-b77dae478cf8,Hr Manager,Human Resources,P3,None,10,1,1.0,Fri Jul 22 2022 13:10:21 GMT+0000 (Coordinated...,"San Francisco, CA",office,employee,807,254,1.00000,200000.0000,USD,270000.0000,NaN,None,70000.0000,USD,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/mozilla.org,Mozilla,mozilla,NaN
4,e983ae47-a1fc-45e8-bdbd-328378dbee06,Hr And Accounting Specialist,Human Resources,None,None,1,1,1.0,Fri Jul 22 2022 13:07:15 GMT+0000 (Coordinated...,"Waterloo, IA",office,employee,637,254,1.00000,49000.0000,USD,49000.0000,NaN,None,NaN,None,None,NaN,male,White,Bachelors degree,None,None,None,False,None,Building Products,None,NaN
5,2158faa0-d3dc-4f2c-ac6d-ebd0e4624fa3,Hr,Human Resources,Middle,Generalist,1,1,1.0,Fri Jul 22 2022 10:09:04 GMT+0000 (Coordinated...,"Minsk, MI, Belarus",hybrid,employee,10015,23,1.00000,10800.0000,USD,10800.0000,NaN,None,NaN,None,None,NaN,female,White,Bachelors degree,None,None,None,False,None,Kernelics,None,NaN
6,6cb7de8e-0f05-4fb7-9057-5b580f911bd8,Senior Professional,Human Resources,CL3,Compensation,10,10,3.0,Thu Jul 21 2022 07:41:02 GMT+0000 (Coordinated...,"Seoul, KG, Korea, South",office,employee,10039,133,1.00000,80000.0000,USD,128000.0000,NaN,None,48000.0000,USD,None,NaN,male,Asian,Bachelors degree,None,None,None,True,https://logo.clearbit.com/samsung.com,Samsung,samsung,NaN
7,6a9f854d-7aca-40fd-a234-81992edd4158,Human Resources,Human Resources,Manager,Business Partner,12,4,1.0,Thu Jul 21 2022 07:30:52 GMT+0000 (Coordinated...,"Bengaluru, KA, India",hybrid,employee,10062,113,79.94698,33163.5179,INR,36479.8659,NaN,None,3316.3480,INR,None,NaN,female,Asian,Masters degree,None,None,[High Performer],True,https://logo.clearbit.com/blueyonder.com,Blue Yonder,blue-yonder,NaN
8,0861001b-3fe1-42c8-ac06-d313040cbda7,Human Resources,Human Resources,None,None,5,1,1.0,Wed Jul 20 2022 23:18:56 GMT+0000 (Coordinated...,"New York, NY",hybrid,employee,501,254,1.00000,75240.0000,USD,82240.0000,NaN,None,7000.0000,USD,None,NaN,female,Black or African American,Bachelors degree,None,None,None,True,https://logo.clearbit.com/nielsen.com,Nielsen,nielsen,NaN
9,287742f7-6486-40c9-a8ca-4a2daf945b0e,HR Program Manager,Human Resources,None,None,15,9,5.0,Wed Jul 20 2022 21:55:20 GMT+0000 (Coordinated...,"Dallas, TX",hybrid,employee,623,254,1.00000,140000.0000,USD,168000.0000,NaN,None,28000.0000,USD,None,NaN,None,None,None,None,None,[High Performer],True,https://logo.clearbit.com/slb.com,Schlumberger,schlumberger,NaN
10,127ea552-e4a3-4ed7-ab85-6d5deb9520a2,Technical Recruiter,Human Resources,None,None,8,1,1.0,Wed Jul 20 2022 16:25:56 GMT+0000 (Coordinated...,"New York, NY",office,employee,501,254,1.00000,129000.0000,USD,141500.0000,12500.0000,USD,NaN,None,None,NaN,male,Two or More Races,Bachelors degree,None,None,None,True,https://logo.clearbit.com/spotify.com,Spotify,spotify,NaN
11,34af16e6-4e6d-4d82-b817-51e642fc7798,Technical Recruiter,Human Resources,Senior,None,4,1,1.0,Tue Jul 19 2022 22:01:38 GMT+0000 (Coordinated...,"Sao Paulo, SP, Brazil",remote,employee,10024,33,1.00000,30000.0000,USD,30000.0000,NaN,None,NaN,None,None,NaN,female,Hispanic / Latino,Bachelors degree,None,None,None,False,None,Bitso,None,NaN
12,ea510aac-b7a1-437d-a7c3-9f268eb61f12,Senior Hcm Consultant,Human Resources,None,None,12,5,2.0,Tue Jul 19 2022 19:11:34 GMT+0000 (Coordinated...,"Atlanta, GA",office,employee,524,254,1.00000,130000.0000,USD,130000.0000,NaN,None,NaN,None,None,NaN,None,None,None,None,None,[H-1B],False,None,EPI-USE,None,NaN
13,071ea0ac-482c-4337-b02f-af8e2518f185,Human Resources,Human Resources,L3,None,10,1,1.0,Tue Jul 19 2022 09:55:26 GMT+0000 (Coordinated...,"Hanoi, HN, Vietnam",office,employee,0,260,1.00000,1500.0000,USD,1500.0000,NaN,None,NaN,None,None,NaN,male,Asian,Bachelors degree,None,None,None,False,None,NGS,None,NaN
14,96f3580b-8e34-432e-9e26-3ccdee12a750,Principal Hrbp,Human Resources,L7,None,15,3,1.0,Mon Jul 18 2022 09:35:37 GMT+0000 (Coordinated...,"Philadelphia, PA",remote,employee,504,254,1.00000,161000.0000,USD,271000.0000,110000.0000,USD,NaN,None,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/amazon.com,Amazon,amazon,NaN
15,01f4468b-990d-4b4a-84f9-6a26beb031ee,Hrbp,Human Resources,L5,None,15,1,1.0,Sat Jul 16 2022 20:26:53 GMT+0000 (Coordinated...,"Austin, TX",office,employee,635,254,1.00000,90000.0000,USD,162000.0000,60000.0000,USD,12000.0000,USD,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/amazon.com,Amazon,amazon,NaN
16,40ac6155-841e-40cd-a6f4-9f8cf2a331fa,Senior Chief,Human Resources,8,None,25,25,3.0,Thu Jul 14 2022 13:06:24 GMT+0000 (Coordinated...,"Pensacola, FL",office,employee,686,254,1.00000,108000.0000,USD,108000.0000,NaN,None,NaN,None,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/navy.mil,U.S. Navy,us-navy,NaN
17,08b33954-c710-4785-a605-c94942f964c9,Head Of Hr,Human Resources,L2,HR operations,25,1,1.0,Thu Jul 14 2022 08:54:23 GMT+0000 (Coordinated...,"Amsterdam, NH, Netherlands",remote,employee,10026,175,0.99808,155297.3945,EUR,155297.3945,NaN,None,NaN,None,None,NaN,female,White,None,None,None,None,False,None,VEED,None,NaN
18,bb4dfdf0-5f3f-41c3-93b8-0e1ef4ccf6aa,Human Resources,Human Resources,L6,None,7,3,1.0,Wed Jul 13 2022 19:06:16 GMT+0000 (Coordinated...,"Detroit, MI",office,employee,505,254,1.00000,140000.0000,USD,158000.0000,NaN,None,18000.0000,USD,None,NaN,male,White,None,None,None,None,True,https://logo.clearbit.com/ford.com,Ford Motor,ford-motor,NaN
19,db5cd827-733b-4543-afe4-46aeda98c7d0,Recruiting Coordinator,Human Resources,L1,None,2,1,1.0,Tue Jul 12 2022 00:50:43 GMT+0000 (Coordinated...,"Austin, TX",hybrid,employee,635,254,1.00000,78000.0000,USD,78000.0000,NaN,None,NaN,None,None,NaN,None,None,None,None,None,None,False,None,Armorblox,None,NaN
20,7f25032e-9682-4860-899c-ffc96343e5d3,Principal Hrbp,Human Resources,L7,None,10,7,2.0,Mon Jul 11 2022 18:39:52 GMT+0000 (Coordinated...,"Seattle, WA",office,employee,819,254,1.00000,165000.0000,USD,265000.0000,100000.0000,USD,NaN,None,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/amazon.com,Amazon,amazon,NaN
21,3d9d924f-7956-40ca-9431-4811efdc54ed,Hr Business Partner,Human Resources,L5,None,10,1,1.0,Mon Jul 11 2022 17:00:48 GMT+0000 (Coordinated...,"Toronto, ON, Canada",hybrid,employee,950,43,1.29930,88509.5379,CAD,88509.5379,NaN,None,NaN,None,None,NaN,None,None,None,None,None,None,False,None,Shaw Communications,None,NaN
22,f1b6a3ed-3bd1-4b57-957f-a1db2d6aec21,Employer Branding,Human Resources,Lead,None,15,1,1.0,Sat Jul 09 2022 17:22:20 GMT+0000 (Coordinated...,"Barcelona, CT, Spain",hybrid,employee,10048,226,0.98175,81487.1403,EUR,94728.8006,13241.6603,EUR,NaN,None,None,NaN,female,Hispanic / Latino,Masters degree,None,None,None,False,None,Veriff,None,NaN
23,e5e158fd-2ebe-45ef-bdd3-be4a5e9b5310,Manager Hr Business Partner,Human Resources,P4,None,8,0,NaN,Sat Jul 09 2022 05:26:51 GMT+0000 (Coordinated...,"Los Angeles, CA",hybrid,employee,803,254,1.00000,130000.0000,USD,139750.0000,NaN,None,9750.0000,USD,None,35000.0,female,Asian,Masters degree,None,None,[Negotiated],True,https://logo.clearbit.com/disney.com,Disney,disney,NaN
24,ef1cb7b1-8c89-4860-975a-79c703a03bdb,Head Of Learning & Development,Human Resources,L4,None,11,2,2.0,Fri Jul 08 2022 15:33:21 GMT+0000 (Coordinated...,"San Francisco, CA",remote,employee,807,254,1.00000,95000.0000,USD,95000.0000,NaN,None,NaN,None,None,NaN,male,Asian,Some college coursework completed,None,None,None,False,None,EyCrowd,None,NaN
25,dfc8d763-9783-4ecb-b3d6-7e5cb47c8d29,Human Resources Advisor,Human Resources,7,None,4,4,4.0,Fri Jul 08 2022 03:35:30 GMT+0000 (Coordinated...,"Ottawa, ON, Canada",hybrid,employee,922,43,1.29975,66551.5159,CAD,66551.5159,NaN,None,NaN,None,None,NaN,female,Asian,Bachelors degree,None,None,None,False,None,Government of Canada,None,NaN
26,0eff7813-8cfd-41c4-896a-1b4e6d275a99,Diversity Business Partner,Human Resources,Manager,Diversity,13,1,1.0,Fri Jul 08 2022 02:11:29 GMT+0000 (Coordinated...,"Tampa, FL",remote,employee,539,254,1.00000,135000.0000,USD,160000.0000,NaN,None,25000.0000,USD,None,NaN,male,Black or African American,Bachelors degree,None,None,None,True,https://logo.clearbit.com/metlife.com,MetLife,metlife,NaN
27,6b61da1e-99de-482f-b2c4-10ffc777eeb3,False,Human Resources,False,False,5-10,0-1,1.0,Fri Jul 08 2022 01:24:15 GMT+0000 (Coordinated...,"Tampa, FL",hybrid,employee,539,254,1.00000,83000.0000,USD,87000.0000,NaN,None,4000.0000,USD,None,NaN,False,False,False,NaN,None,None,NaN,NaN,NaN,NaN,False
28,6f53221a-8a2d-41cd-99bc-77635787791b,False,Human Resources,None,None,11,1,1.0,Wed Jul 06 2022 09:05:03 GMT+0000 (Coordinated...,"London, EN, United Kingdom",hybrid,employee,10045,253,0.83495,77848.9730,GBP,77848.9730,NaN,None,NaN,None,None,NaN,male,Two or More Races,Bachelors degree,NaN,None,[Stock Appreciation],NaN,NaN,NaN,NaN,False
29,709dc441-37a9-4b8c-831f-acc6fcba19b7,Head Of Talent,Human Resources,L5,None,10,0,NaN,Mon Jul 04 2022 20:24:51 GMT+0000 (Coordinated...,"Lima, LI, Peru",hybrid,employee,0,194,1.00000,90000.0000,USD,157500.0000,NaN,None,67500.0000,USD,None,NaN,female,Hispanic / Latino,Bachelors degree,None,None,None,False,None,Krealo,None,NaN
30,bf87fcf6-a782-408e-8636-fe9c3997055b,Recruiting Coordinator,Human Resources,L4,None,1,1,1.0,Mon Jul 04 2022 19:50:36 GMT+0000 (Coordinated...,"New York, NY",remote,employee,501,254,1.00000,70720.0000,USD,90720.0000,10000.0000,USD,10000.0000,USD,None,NaN,female,White,Bachelors degree,None,None,None,True,https://logo.clearbit.com/amazon.com,Amazon,amazon,NaN
31,00590952-3248-43ce-b5c3-6a88794ce9a9,Hr Analysr,Human Resources,None,None,4,1,1.0,Mon Jul 04 2022 15:19:09 GMT+0000 (Coordinated...,"San Antonio, TX",hybrid,employee,641,254,1.00000,52000.0000,USD,52000.0000,NaN,None,NaN,None,None,NaN,None,None,Masters degree,None,None,None,False,None,City of San Antonio,None,NaN
32,1a9bae13-e91f-4337-bff8-40359edfca74,Human Resources,Human Resources,None,None,10,1,1.0,Sun Jul 03 2022 12:49:22 GMT+0000 (Coordinated...,"Skopje, AR, Macedonia, The Former Yugoslav Rep...",hybrid,employee,0,146,0.95890,26071.4316,EUR,28157.1461,NaN,None,2085.7145,EUR,None,NaN,male,White,Masters degree,None,None,None,False,None,HSO,None,NaN
33,a4a4b6ad-4422-4348-a4ea-5383e0da18bd,Ux Recruiter,Human Resources,Junior,None,1,0,NaN,Fri Jul 01 2022 15:59:16 GMT+0000 (Coordinated...,"Dallas, TX",hybrid,employee,623,254,1.00000,50000.0000,USD,50000.0000,NaN,None,NaN,None,None,NaN,None,None,None,None,None,None,False,None,Photon,None,NaN
34,2d08d55b-3d61-4d10-82e2-0c086067474a,False,Human Resources,False,False,2-4,0-1,NaN,Fri Jul 01 2022 06:59:59 GMT+0000 (Coordinated...,"Santa Monica, CA",remote,offer,803,254,1.00000,80000.0000,USD,80000.0000,NaN,None,NaN,None,None,5000.0,False,False,False,NaN,None,[Negotiated],NaN,NaN,NaN,NaN,False
35,eebbfb06-91e1-466d-b98d-4b8221bbe0e3,False,Human Resources,False,False,5-10,0-1,NaN,Fri Jul 01 2022 06:59:59 GMT+0000 (Coordinated...,"San Francisco, CA",remote,offer,807,254,1.00000,280000.0000,USD,440510.0000,86760.0000,None,73750.0000,USD,None,NaN,False,False,False,NaN,"[{'percent': 50, 'occurrences': 1}, {'percent'...",None,NaN,NaN,NaN,NaN,False
36,9db6d9ee-454b-4e2a-bafd-fd36affb51ae,HR Partner,Human Resources,L4,None,3,2,2.0,Fri Jul 01 2022 04:59:59 GMT+0000 (Coordinated...,"Chicago, IL",office,employee,602,254,1.00000,52000.0000,USD,62000.0000,3000.0000,USD,7000.0000,USD,None,NaN,female,White,Bachelors degree,None,None,[High Performer],True,https://logo.clearbit.com/amazon.com,Amazon,amazon,NaN
37,588e5929-f5ed-411f-9dd4-6ce3f1eb04fa,Talent Sourcer,Human Resources,L5,None,4,1,1.0,Fri Jul 01 2022 04:34:48 GMT+0000 (Coordinated...,"Toronto, ON, Canada",remote,employee,950,43,1.00000,70000.0000,USD,90000.0000,15000.0000,USD,5000.0000,USD,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/shopify.com,Shopify,shopify,NaN
38,322e9525-80f2-4d9f-8df1-85398c7302e3,Sr. HRBP,Human Resources,None,HRBP,15,4,2.0,Fri Jul 01 2022 03:59:59 GMT+0000 (Coordinated...,"Toronto, ON, Canada",office,employee,950,43,1.00000,125000.0000,USD,134696.1235,NaN,None,9696.1235,CAD,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/flipp.com,Flipp,flipp,NaN
39,22319514-7d49-4162-9f78-8e5e2a34b072,False,Human Resources,None,None,3,0,NaN,Fri Jul 01 2022 03:59:59 GMT+0000 (Coordinated...,"San Francisco, CA",remote,offer,807,254,1.00000,102645.0000,USD,102645.0000,NaN,None,NaN,None,None,NaN,female,White,None,Education: Juris Doctor (J.D),None,None,NaN,NaN,NaN,NaN,False
40,1e6f10d8-babf-45c8-8d63-727053854d72,Director,Human Resources,L7,None,16,1,1.0,Fri Jul 01 2022 01:01:50 GMT+0000 (Coordinated...,"Mountain View, CA",office,employee,807,254,1.00000,120000.0000,USD,240000.0000,NaN,None,120000.0000,USD,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/samsung.com,Samsung,samsung,NaN
41,4c09d025-51bf-4733-85ef-0efa336ec202,Human Resources,Human Resources,L5,None,10,0,NaN,Thu Jun 30 2022 22:43:12 GMT+0000 (Coordinated...,"Los Angeles, CA",remote,offer,803,254,1.00000,154000.0000,USD,235850.0000,53750.0000,USD,28100.0000,USD,None,100000.0,female,None,Masters degree,None,"[{'percent': 33, 'occurrences': 12}, {'percent...",[Negotiated],True,https://logo.clearbit.com/google.com,Google,google,NaN
42,5aebc565-3e57-459f-a42b-865742a37672,False,Human Resources,False,None,5-10,5-10,6.0,Thu Jun 30 2022 21:47:39 GMT+0000 (Coordinated...,"Detroit, MI",hybrid,employee,505,254,1.00000,93100.0000,USD,102410.0000,NaN,None,9310.0000,USD,None,NaN,False,False,False,NaN,None,None,NaN,NaN,NaN,NaN,False
43,3e753f12-f719-446c-a8e0-999df305a59a,Human Resources,Human Resources,None,None,10,5,5.0,Thu Jun 30 2022 20:55:30 GMT+0000 (Coordinated...,"Washington, DC",hybrid,employee,511,254,1.00000,124000.0000,USD,124000.0000,NaN,None,NaN,None,None,NaN,female,Black or African American,Bachelors degree,None,None,None,True,https://logo.clearbit.com/leidos.com,Leidos,leidos,NaN
44,6494c2cc-859a-4129-94db-baf55abedad5,Onboarding Program Manager,Human Resources,L5,None,6,2,0.0,Thu Jun 30 2022 04:59:26 GMT+0000 (Coordinated...,"Seattle, WA",hybrid,employee,819,254,1.00000,73000.0000,USD,85800.0000,12800.0000,USD,NaN,None,None,NaN,female,None,Masters degree,None,None,[Promotion],True,https://logo.clearbit.com/amazon.com,Amazon,amazon,NaN
45,afd1c8b1-8d2e-4504-8071-b7cf936c5435,Human Resources Specialist,Human Resources,L4,None,2,1,1.0,Tue Jun 28 2022 14:21:36 GMT+0000 (Coordinated...,"Toronto, ON, Canada",remote,employee,950,43,1.28436,42044.4503,CAD,59952.2718,11679.0140,CAD,6228.8075,CAD,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/amazon.com,Amazon,amazon,NaN
46,3345dede-bee9-4158-a086-fd791829f8f9,Project Manager,Human Resources,IC6,Human Resources,9,0,NaN,Tue Jun 28 2022 11:16:41 GMT+0000 (Coordinated...,"New York, NY",remote,offer,501,254,1.00000,190000.0000,USD,268000.0000,35000.0000,USD,43000.0000,USD,None,NaN,female,Black or African American,Masters degree,None,"[{'percent': 25, 'occurrences': 4}, {'percent'...",None,True,https://logo.clearbit.com/facebook.com,Facebook,facebook,NaN
47,81174c60-6921-44a0-95e5-0c0e7a798f80,Sr Program Manager,Human Resources,63,Talent Intelligence,8,1,1.0,Tue Jun 28 2022 04:09:43 GMT+0000 (Coordinated...,"San Francisco, CA",remote,employee,807,254,1.00000,175000.0000,USD,215000.0000,25000.0000,USD,15000.0000,USD,None,NaN,female,Asian,Bachelors degree,None,None,None,True,https://logo.clearbit.com/microsoft.com,Microsoft,microsoft,NaN

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df.head()

,uuid,title,jobFamily,level,focusTag,yearsOfExperience,yearsAtCompany,yearsAtLevel,offerDate,location,workArrangement,compPerspective,dmaId,countryId,exchangeRate,baseSalary,baseSalaryCurrency,totalCompensation,avgAnnualStockGrantValue,stockGrantCurrency,avgAnnualBonusValue,bonusCurrency,salesComp,negotiatedAmount,gender,ethnicity,education,otherDetails,vestingSchedule,tags,companyInfo.registered,companyInfo.icon,companyInfo.name,companyInfo.slug,companyInfo
0,d053142e-f3ee-4ce3-a70f-2e41a41963ce,Total Rewards Director,Human Resources,None,None,22,1,1.0,Tue Jul 26 2022 17:13:58 GMT+0000 (Coordinated...,"New York, NY",remote,employee,501,254,1.0,230000.0,USD,276000.0,NaN,None,46000.0,USD,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/thirtymadison.com,Thirty Madison,thirty-madison,NaN
1,d90a1b83-5175-4862-b6ab-6f88dc96b8e8,False,Human Resources,None,None,22,3,2.0,Sun Jul 24 2022 00:19:09 GMT+0000 (Coordinated...,"Minneapolis, MN",remote,employee,613,254,1.0,190000.0,USD,278000.0,50000.0,USD,38000.0,USD,None,NaN,None,None,None,NaN,None,None,NaN,NaN,NaN,NaN,False
2,1a2103dc-5091-49f5-ba07-19f8ecacb543,False,Human Resources,False,False,5-10,2-4,2.0,Fri Jul 22 2022 17:11:28 GMT+0000 (Coordinated...,"San Francisco, CA",hybrid,employee,807,254,1.0,138000.0,USD,138000.0,NaN,None,NaN,None,None,NaN,None,None,None,NaN,None,None,True,https://logo.clearbit.com/twitter.com,Twitter,twitter,NaN
3,801e091f-18ca-4f5e-a8a6-b77dae478cf8,Hr Manager,Human Resources,P3,None,10,1,1.0,Fri Jul 22 2022 13:10:21 GMT+0000 (Coordinated...,"San Francisco, CA",office,employee,807,254,1.0,200000.0,USD,270000.0,NaN,None,70000.0,USD,None,NaN,None,None,None,None,None,None,True,https://logo.clearbit.com/mozilla.org,Mozilla,mozilla,NaN
4,e983ae47-a1fc-45e8-bdbd-328378dbee06,Hr And Accounting Specialist,Human Resources,None,None,1,1,1.0,Fri Jul 22 2022 13:07:15 GMT+0000 (Coordinated...,"Waterloo, IA",office,employee,637,254,1.0,49000.0,USD,49000.0,NaN,None,NaN,None,None,NaN,male,White,Bachelors degree,None,None,None,False,None,Building Products,None,NaN

In [4]:
#pip install azure-storage-blob
from azure.storage.blob import BlobServiceClient, ContainerClient, BlobClient
import os

# Replace with your storage account connection string
connection_string = "<your_connection_string>"
container_name = "<your_container_name>"
destination_folder = "<destination_folder>"

# Create a BlobServiceClient using the connection string
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

# Get a reference to the container
container_client = blob_service_client.get_container_client(container_name)

# List all blobs in the container
blob_list = container_client.list_blobs()

# Download each blob to the specified destination folder
for blob in blob_list:
    # Get the reference to the blob
    blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob.name)

    # Download the blob to the destination folder
    destination_file = os.path.join(destination_folder, blob.name)
    with open(destination_file, "wb") as file:
        data = blob_client.download_blob()
        data.readinto(file)

print(f"Downloaded all files from '{container_name}' to '{destination_folder}'.")

ValueError: Connection string is either blank or malformed.